# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:

services:
 
  create:
    build:
      context: ./accountModule
       #Api  Service
        #Use the DockerFile in that Directory
      dockerfile: Dockerfile
    #This Service Depends on the database service specifed above
    depends_on: 
      - json
    #Map port 8888 in the docker container to port 80 in the Api
    ports:
      - "5001:80"
    restart: always
    #Specify Environment Variables for the Api Service
    environment: 
      
      - ASPNETCORE_ENVIRONMENT=Development
  
